<?php

namespace PackageVersions;

/**
 * This class is generated by ocramius/package-versions, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Versions
{
    const ROOT_PACKAGE_NAME = '__root__';
    const VERSIONS = array (
  'doctrine/annotations' => 'v1.6.0@c7f2050c68a9ab0bdb0f98567ec08d80ea7d24d5',
  'doctrine/cache' => 'v1.8.0@d768d58baee9a4862ca783840eca1b9add7a7f57',
  'doctrine/collections' => 'v1.5.0@a01ee38fcd999f34d9bfbcee59dbda5105449cbf',
  'doctrine/common' => 'v2.10.0@30e33f60f64deec87df728c02b107f82cdafad9d',
  'doctrine/dbal' => 'v2.8.0@5140a64c08b4b607b9bedaae0cedd26f04a0e621',
  'doctrine/doctrine-bundle' => '1.10.0@82d2c63cd09acbde2332f55d9aa7b28aefe4983d',
  'doctrine/doctrine-cache-bundle' => '1.3.5@5514c90d9fb595e1095e6d66ebb98ce9ef049927',
  'doctrine/doctrine-migrations-bundle' => 'v1.3.1@a9e506369f931351a2a6dd2aef588a822802b1b7',
  'doctrine/event-manager' => 'v1.0.0@a520bc093a0170feeb6b14e9d83f3a14452e64b3',
  'doctrine/inflector' => 'v1.3.0@5527a48b7313d15261292c149e55e26eae771b0a',
  'doctrine/instantiator' => '1.1.0@185b8868aa9bf7159f5f953ed5afb2d7fcdc3bda',
  'doctrine/lexer' => 'v1.0.1@83893c552fd2045dd78aef794c31e694c37c0b8c',
  'doctrine/migrations' => 'v1.8.1@215438c0eef3e5f9b7da7d09c6b90756071b43e6',
  'doctrine/orm' => 'v2.6.3@434820973cadf2da2d66e7184be370084cc32ca8',
  'doctrine/persistence' => 'v1.1.0@c0f1c17602afc18b4cbd8e1c8125f264c9cf7d38',
  'doctrine/reflection' => 'v1.0.0@02538d3f95e88eb397a5f86274deb2c6175c2ab6',
  'jdorn/sql-formatter' => 'v1.2.17@64990d96e0959dff8e059dfcdc1af130728d92bc',
  'ocramius/package-versions' => '1.3.0@4489d5002c49d55576fa0ba786f42dbb009be46f',
  'ocramius/proxy-manager' => '2.1.1@e18ac876b2e4819c76349de8f78ccc8ef1554cd7',
  'psr/cache' => '1.0.1@d11b50ad223250cf17b86e38383413f5a6764bf8',
  'psr/container' => '1.0.0@b7ce3b176482dbbc1245ebf52b181af44c2cf55f',
  'psr/log' => '1.1.0@6c001f1daafa3a3ac1d8ff69ee4db8e799a654dd',
  'psr/simple-cache' => '1.0.1@408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
  'sensio/framework-extra-bundle' => 'v5.2.2@9ef408febe2f12e70118ef61c6515035a06c5830',
  'symfony/asset' => 'v4.2.0@fb06338fd3762f8615b51a58e5e9299ccca03876',
  'symfony/cache' => 'v4.2.0@dbe98af4943a9c246e4538868e0fa55bc8b5e0f3',
  'symfony/config' => 'v4.2.0@10ba96d42cc9a482bce05c8179f06e24e665c920',
  'symfony/console' => 'v4.2.0@4dff24e5d01e713818805c1862d2e3f901ee7dd0',
  'symfony/contracts' => 'v1.0.0@4a33574d5771f4b04334cd4f7d43de96a92efb62',
  'symfony/debug' => 'v4.2.0@e0a2b92ee0b5b934f973d90c2f58e18af109d276',
  'symfony/dependency-injection' => 'v4.2.0@c2061bce5915f853a619f02ce1278ca83156d375',
  'symfony/doctrine-bridge' => 'v4.2.0@9f66793ce023d1c2b50ba6f3141dacf54ad2f651',
  'symfony/dotenv' => 'v4.2.0@97f135ab40f969cbeae27d482ff63acbc33dbe2a',
  'symfony/event-dispatcher' => 'v4.2.0@9b788b5f7cd6be22918f3d18ee3ff0a78e060137',
  'symfony/filesystem' => 'v4.2.0@2f4c8b999b3b7cadb2a69390b01af70886753710',
  'symfony/finder' => 'v4.2.0@e53d477d7b5c4982d0e1bfd2298dbee63d01441d',
  'symfony/flex' => 'v1.1.8@955774ecf07b10230bb5b44e150ba078b45f68fa',
  'symfony/form' => 'v4.2.0@e098c91c7daec1e9da3ffd95164d778ab32f9796',
  'symfony/framework-bundle' => 'v4.2.0@6953f43de8244c601884b1a0ecbae1a2be32838f',
  'symfony/http-foundation' => 'v4.2.0@1b31f3017fadd8cb05cf2c8aebdbf3b12a943851',
  'symfony/http-kernel' => 'v4.2.0@500409e5d8a31fc92450a0ec2ea4e4c35af40117',
  'symfony/inflector' => 'v4.2.0@f9a637c0359f74404d44cf0da0a3ce53bae0787e',
  'symfony/intl' => 'v4.2.0@1730183319d8b1f74143a3ed16473b229dc94cec',
  'symfony/options-resolver' => 'v4.2.0@a9c38e8a3da2c03b3e71fdffa6efb0bda51390ba',
  'symfony/orm-pack' => 'v1.0.5@1b58f752cd917a08c9c8df020781d9c46a2275b1',
  'symfony/polyfill-intl-icu' => 'v1.10.0@f22a90256d577c7ef7efad8df1f0201663d57644',
  'symfony/polyfill-mbstring' => 'v1.10.0@c79c051f5b3a46be09205c73b80b346e4153e494',
  'symfony/property-access' => 'v4.2.0@b6df4e1849f389468edb36e2e59877d4a8170723',
  'symfony/routing' => 'v4.2.0@97b9f457df748357eec101df5c8b1c649b543241',
  'symfony/security-bundle' => 'v4.2.0@705b5852306fb2bbf3b7903e7929eed01fc2c9d9',
  'symfony/security-core' => 'v4.2.0@faad8794fb93779a32d41cd312265480a417b375',
  'symfony/security-csrf' => 'v4.2.0@0aed738ad254d8bad49f845cfaf3984079934967',
  'symfony/security-guard' => 'v4.2.0@62335fd15d9f1289b1ebaff0ae72ebd9fcac3dd2',
  'symfony/security-http' => 'v4.2.0@34e089af7d363bd2ded8ad15f06b2b97348b97e5',
  'symfony/twig-bridge' => 'v4.2.0@c0aea0ffe3417d5b4fbdb2346f79e5d1abe63ab9',
  'symfony/twig-bundle' => 'v4.2.0@2842f70b899ab765b3eaccdd3b8cdbb0cbb69fb6',
  'symfony/var-exporter' => 'v4.2.0@08250457428e06289d21ed52397b0ae336abf54b',
  'symfony/yaml' => 'v4.2.0@c41175c801e3edfda90f32e292619d10c27103d7',
  'twig/twig' => 'v2.5.0@6a5f676b77a90823c2d4eaf76137b771adf31323',
  'zendframework/zend-code' => '3.3.1@c21db169075c6ec4b342149f446e7b7b724f95eb',
  'zendframework/zend-eventmanager' => '3.2.1@a5e2583a211f73604691586b8406ff7296a946dd',
  'doctrine/data-fixtures' => 'v1.3.1@3a1e2c3c600e615a2dffe56d4ca0875cc5233e0a',
  'doctrine/doctrine-fixtures-bundle' => '3.0.4@0438f8dd0a21bc5325c6be3ae0a09131815e10d4',
  'nikic/php-parser' => 'v4.1.0@d0230c5c77a7e3cfa69446febf340978540958c0',
  'symfony/maker-bundle' => 'v1.9.0@e873047b6022a0343c9354f65d5d47b9e351dd53',
  'symfony/process' => 'v4.2.0@2b341009ccec76837a7f46f59641b431e4d4c2b0',
  'symfony/web-server-bundle' => 'v4.2.0@6291444989fc753df2a9c86e5f6d5af4616804f5',
  'paragonie/random_compat' => '2.*@',
  'symfony/polyfill-ctype' => '*@',
  'symfony/polyfill-iconv' => '*@',
  'symfony/polyfill-php71' => '*@',
  'symfony/polyfill-php70' => '*@',
  'symfony/polyfill-php56' => '*@',
  '__root__' => 'No version set (parsed as 1.0.0)@',
);

    private function __construct()
    {
    }

    /**
     * @throws \OutOfBoundsException if a version cannot be located
     */
    public static function getVersion(string $packageName) : string
    {
        if (isset(self::VERSIONS[$packageName])) {
            return self::VERSIONS[$packageName];
        }

        throw new \OutOfBoundsException(
            'Required package "' . $packageName . '" is not installed: cannot detect its version'
        );
    }
}
